<?php

function dw(){
  echo '<pre>';
  echo base64_decode('RFdEVyAgICAgICAgICBEVyAgICAgICAgICBEVw0KRFcgIERXICAgICAgICBEVyAgICAgICAgICBEVw0KRFcgICAgRFcgICAgICBEVyAgICBEVyAgICBEVw0KRFcgICAgRFcgICAgICBEVyAgRFdEV0RXICBEVw0KRFcgIERXICAgICAgICBEV0RXICAgICAgRFdEVw0KRFdEVyAgICAgICAgICBEVyAgICAgICAgICBEVw==');
  echo '</pre>';
}
dw();

?>
